import type { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Bloglist from '../../components/Bloglist'
import { getAllCategories } from '../../data'
import { Category } from '../../lib/types'

const CategoryPage = ({
  category,
}: InferGetStaticPropsType<typeof getStaticProps>) => (
  <>
    <Head>
      <title>{(category as Category).name}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Bloglist category={category} />
  </>
)

export const getStaticPaths = async () => ({
  paths: (await getAllCategories()).map((category) => ({
    params: { slug: category.slug },
  })),
  fallback: false,
})

export const getStaticProps = async ({
  params,
}: {
  params: { slug: string }
}) => {
  const category = (await getAllCategories()).find(
    (_category) => _category.slug === params.slug
  )
  return { props: { category } }
}

export default CategoryPage
