import type { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import BlogPost from '../../components/BlogPost/BlogPost'
import { Blog, getAllCategories } from '../../data'

const ArticlePage = ({
  blog,
}: InferGetStaticPropsType<typeof getStaticProps>) => (
  <>
    <Head>
      <title>{(blog as Blog).title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <BlogPost blog={blog} />
  </>
)

export const getStaticPaths = async () => ({
  paths: (await getAllCategories())
    .flatMap((category) => category.blogs)
    .map((p) => ({ params: { slug: p.slug } })),
  fallback: false,
})

export const getStaticProps = async ({
  params,
}: {
  params: { slug: string }
}) => {
  const blog = (await getAllCategories())
    .flatMap((category) => category.blogs)
    .find((_blog) => _blog.slug === params.slug)
  return { props: { blog } }
}

export default ArticlePage
